---
stages:
  - syntax
  - unit
  - acceptance
  - build

cache:
  paths:
    - vendor/bundle

validate:
  stage: syntax
  tags:
    - pdk
  except:
    - tags
    - /^master$/
  script:
    - pdk validate --format=text:stdout --parallel --puppet-version=5.5
    - pdk validate --format=text:stdout --parallel --puppet-version=6.21
    - pdk validate --format=text:stdout --parallel --pe-version=2018.1
    - pdk validate --format=text:stdout --parallel --pe-version=2019.8

test_unit:
  stage: unit
  tags:
    - pdk
  except:
    - tags
    - /^master$/
  when: on_success
  script:
    - pdk test unit --format=text:stdout --puppet-version=5.5
    - pdk test unit --format=text:stdout --puppet-version=6.21
    - pdk test unit --format=text:stdout --pe-version=2018.1
    - pdk test unit --format=text:stdout --pe-version=2019.8

acceptance-Ruby 2.5.8-Puppet ~> 6.21:
  stage: acceptance
  when: on_success
  except:
    - tags
    - /^master$/
  tags:
    - pdk
  script:
    - rm -f Gemfile.lock
    - . /etc/profile
    - rvm use 2.5.8
    - gem update --system
    - bundle config set path 'vendor/bundle'
    - bundle install --jobs $(nproc)
    - bundle update --bundler
    - bundle exec rake beaker:default
  cache:
    paths:
      - vendor/bundle

build:
  stage: build
  tags:
    - pdk
  only:
    - tags
  script:
    - rm -f Gemfile.lock
    - . /etc/profile
    - rvm use 2.5.8
    - gem update --system
    - bundle config set path 'vendor/bundle'
    - bundle install --jobs $(nproc)
    - bundle update --bundler
    - mkdir builds/
    - bundle exec rake module:bump_to_version[${CI_COMMIT_TAG}]
    - rm -f Gemfile.lock
    - pdk build --target-dir=builds/
  variables:
    PDK_PUPPET_VERSION: '6.17'
    PUPPET_GEM_VERSION: '~> 6.17'
  cache:
    paths:
      - vendor/bundle
  artifacts:
    paths:
      - builds/phoenixnap-ca_trust*
